print("Hi")
user = input("Whats your name??")
location = input('Where are you from?')
print('Oh, ok', user)
print('Did you know that', location, 'is a cool country!')
print('I like', location, 'you know?')
print("Anyways", user, "I wanna show you something cool...", sep= '\n')
print('Check this out')
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print('TA DA!!!')
print()
print()
print('PPPPP  Y   Y  TTTTT  H   H  OOOOO  N    N')
print('PP  P   Y Y     T    H   H  O   O  N N  N')
print('PPPPP    Y      T    HHHHH  O   O  N  N N')
print('P        Y      T    H   H  O   O  N   NN')
print('P        Y      T    H   H  OOOOO  N    N')
print('                                           Its so cool!')
print()
print()
print()
print()
print()
print()
print()
print('SEE, I TOLD YOU!!!')
print()
print()
print('Anyways...')
print()
print()
print('BYE', user,'!')
print('HOPE YOU HAVE A NICE DAY!!!!!')
print('PEACE OUT!')